"use client";
import { useRef, useState } from 'react';
import { emptySignature, exampleSignature, signatureHtml, type SignatureData } from '@/lib/email-signature';
import './signature.css';
const providers = [
  { name: 'Gmail', icon: 'M', color: '#db4437', subtitle: 'Google Workspace & personal', steps: ['Open Gmail on your computer. Select Settings → See all settings.', 'In General, scroll to Signature. Click Create new and give your signature a name.', 'Paste your copied signature into the editor. Under Signature defaults, choose it for new emails and replies.', 'Scroll down and click Save Changes. Compose a new message to check your signature.'], url: 'https://support.google.com/mail/answer/8395?hl=en' },
  { name: 'Outlook', icon: 'O', color: '#0078d4', subtitle: 'Web & new Outlook', steps: ['Open Outlook Settings → Accounts → Signatures. Some versions show Mail → Compose and reply.', 'Choose your account, add a signature and give it a name.', 'Paste your copied signature into the editor. Choose it as the default for new messages and replies.', 'Save your changes and compose a new message. For classic Windows Outlook, use File → Options → Mail → Signatures.'], url: 'https://support.microsoft.com/en-us/outlook/mail/how-to-add-and-change-an-email-signature-in-outlook' },
  { name: 'Apple Mail', icon: '✉', color: '#1599ed', subtitle: 'Mail on macOS', steps: ['On your Mac, open Mail → Settings → Signatures.', 'Select your email account and click + to create a signature.', 'Turn off “Always match my default message font”, then paste the copied signature into the preview area.', 'Choose your new signature in the Choose Signature menu. Open a new message to check it.'], url: 'https://support.apple.com/guide/mail/mail11943/mac' },
  { name: 'Other email app', icon: '@', color: '#7760bb', subtitle: 'HTML-compatible email clients', steps: ['Open your email app’s settings and find the Signature section.', 'Copy the formatted signature and paste it into the rich-text signature editor.', 'If your app accepts HTML source, use Download HTML and import the file or its source instead.', 'Save, choose your default signature, and send yourself a test email. Plain-text-only apps cannot preserve the design.'], url: '' },
];
export default function EmailSignature() {
  const [data, setData] = useState<SignatureData>(emptySignature);
  const [step, setStep] = useState(0), [provider, setProvider] = useState(0), [notice, setNotice] = useState('');
  const preview = useRef<HTMLDivElement>(null);
  const html = signatureHtml(data);
  function update(key: keyof SignatureData, value: string) { setData(d => ({ ...d, [key]: value })); setNotice(''); }
  async function copy() {
    try {
      if (!navigator.clipboard?.write || typeof ClipboardItem === 'undefined') throw new Error();
      await navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob([html], { type: 'text/html' }), 'text/plain': new Blob([preview.current?.innerText || data.name], { type: 'text/plain' }) })]);
      setNotice('Signature copied. Paste it into your email app using the steps below.');
    } catch {
      const selection = window.getSelection(); const range = document.createRange();
      if (preview.current && selection) { range.selectNodeContents(preview.current); selection.removeAllRanges(); selection.addRange(range); }
      setNotice('Automatic copying is unavailable. Your signature is selected: press Ctrl+C or ⌘C, then paste it into your email app.');
    }
  }
  function download() { const url = URL.createObjectURL(new Blob([`<!doctype html><html><head><meta charset="utf-8"><title>Email signature</title></head><body>${html}</body></html>`], { type: 'text/html' })); const a = document.createElement('a'); a.href = url; a.download = 'email-signature.html'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <main id="main-content" className="sig-page">
    <section className="sig-hero"><span className="sig-pill">A little detail. A lasting impression.</span><h1>Make every email<br/>feel like <em>you.</em></h1><p>Your details. Your design. A beautiful signature for every conversation.</p><a href="#signature-builder" className="mk-button">Create your free signature <span>↗</span></a><div className="sig-compatible">Works with <b className="sig-gmail">M</b> Gmail <b className="sig-outlook">O</b> Outlook <b>✉</b> Apple Mail</div></section>
    <section id="signature-builder" className="sig-builder" aria-label="Email signature builder">
      <div className="sig-editor"><div className="sig-steps">{['Your details', 'Your design', 'Install'].map((label, i) => <button key={label} aria-current={step === i ? 'step' : undefined} disabled={i > 0 && !data.name.trim()} onClick={() => {setStep(i); setNotice('');}}><span>{i + 1}</span>{label}</button>)}</div>
        {step < 2 ? <form onSubmit={e => {e.preventDefault(); setStep(step + 1);}}><p className="mk-eyebrow">{step === 0 ? '01 / Make the introduction' : '02 / Make it yours'}</p><h2>{step === 0 ? 'Start with the essentials.' : 'Find your signature style.'}</h2><p className="sig-muted">{step === 0 ? 'Add your details and watch your signature come to life.' : 'Keep it simple. Make it unmistakably yours.'}</p>
          {step === 0 ? <><div className="sig-fields">{([['name','Full name','Alex Morgan'],['title','Job title','Creative Director'],['company','Company','Studio North'],['email','Email address','alex@company.com'],['phone','Phone number','+256 700 000 000'],['website','Website URL','https://yourcompany.com'],['photo','Photo or logo URL','https://…/photo.jpg'],['link','Digital card or booking URL','https://…']] as const).map(([key,label,placeholder]) => <label key={key}>{label}{key === 'name' && ' *'}<input value={data[key]} required={key === 'name'} type={key === 'email' ? 'email' : ['website','photo','link'].includes(key) ? 'url' : 'text'} placeholder={placeholder} onChange={e => update(key,e.target.value)} maxLength={key === 'photo' ? 2000 : 300}/></label>)}</div><p className="sig-note">Use a publicly accessible image URL so it can appear in recipients’ inboxes. Your details stay on this page; reload clears them.</p></> : <><fieldset><legend>Layout</legend><div className="sig-layouts">{['classic','stacked','minimal'].map(layout => <button type="button" key={layout} aria-pressed={data.layout === layout} onClick={() => update('layout',layout)}><span className={`sig-layout-art ${layout}`}><i/><span><b/><b/><b/></span></span>{layout}</button>)}</div></fieldset><div className="sig-fields"><label>Brand color<div className="sig-color"><input aria-label="Brand color" type="color" value={data.color} onChange={e => update('color',e.target.value)}/><span>{data.color}</span></div></label><label>Font<select value={data.font} onChange={e => update('font',e.target.value)}>{['Arial','Georgia','Verdana'].map(font => <option key={font}>{font}</option>)}</select></label><label>Link label<input value={data.cta} onChange={e => update('cta',e.target.value)} maxLength={80}/></label></div></>}
          <div className="sig-form-actions">{step === 0 ? <button type="button" className="sig-text-button" onClick={() => setData(exampleSignature)}>Try sample details</button> : <button type="button" className="sig-text-button" onClick={() => setStep(0)}>← Your details</button>}<button className="mk-button" type="submit">{step === 0 ? 'Choose your design' : 'Set up in your email'} →</button></div></form> : <div className="sig-install"><p className="mk-eyebrow">03 / Ready to send</p><h2>Meet your new sign-off.</h2><p className="sig-muted">Choose your email app. Copy your signature, then follow the steps to add it.</p><div className="sig-providers">{providers.map((p,i) => <button key={p.name} aria-pressed={provider === i} onClick={() => setProvider(i)}><span style={{background:p.color}}>{p.icon}</span><strong>{p.name}<small>{p.subtitle}</small></strong><b>{provider === i ? '✓' : '›'}</b></button>)}</div><button className="mk-button" onClick={copy}>Copy signature <span>⧉</span></button><ol className="sig-instructions">{providers[provider].steps.map(s => <li key={s}>{s}</li>)}</ol>{providers[provider].url && <a className="sig-text-button" href={providers[provider].url} target="_blank" rel="noreferrer">Official {providers[provider].name} guide ↗</a>}<p className="sig-note">Send a test email to check the result. Email apps may adjust spacing or block images. After editing here, copy and install your signature again.</p></div>}
      </div><aside className="sig-preview-pane"><div className="sig-preview-label"><span>LIVE PREVIEW</span><span className="sig-live">● Updates as you type</span></div><div className="sig-email"><div className="sig-email-bar"><span><i/><i/><i/></span><span>New message</span><span>↗</span></div><div className="sig-email-meta">To <span>your next connection</span></div><div className="sig-email-meta">Subject <span>A great first impression</span></div><div className="sig-email-body"><p>Hello there,</p><p>Looking forward to connecting with you.</p><p>Best,</p><div ref={preview} className="sig-render" dangerouslySetInnerHTML={{__html: data.name ? html : signatureHtml(exampleSignature)}}/></div><div className="sig-email-bottom"><span>Send ↗</span><span>Ａ　♧　⋯</span></div></div><p className="sig-preview-caption">{data.name ? 'Looking good. This is how you’ll sign off.' : 'An example of what’s possible. Add your details to make it yours.'}</p>{step === 2 && <button className="sig-download" onClick={download}>Download HTML ↓</button>}<p role="status" className="sig-status">{notice}</p></aside>
    </section><section className="sig-how"><p className="mk-eyebrow">Small effort. Every email.</p><h2>From introduction to inbox.</h2><div>{[['01','Create','Bring your name, work and contact links together.'],['02','Customize','Choose a layout, font and color that feel like your brand.'],['03','Install','Copy your signature and follow the guide for your email app.']].map(([n,title,body]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  </main>;
}
